server {
    listen 8080;
    listen [::]:8080;
    root /usr/share/nginx/html;
    index index.html;
    location ^~ /pathway/content/ {
        deny all;
        return 404;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
