window.northstarRulesData = {
  scenarios: [
    {
      title: 'Korea -> Canada Junior A tryout',
      countries: ['Korea', 'Canada'],
      leagues: ['Junior A', 'LHJQ', 'LHJAAAQ'],
      agencies: ['Korean Hockey Federation', 'Hockey Canada', 'Hockey Quebec', 'LHJQ/LHJAAAQ'],
      risk: 'High',
      confidence: 'Needs written confirmation',
      answer: 'Written federation and league clearance is required before the player skates. A recent Canada Junior A tryout case showed that a KHF permission letter may be required even for a 15-day tryout.',
      actions: ['Confirm with Hockey Quebec/LHJQ/LHJAAAQ registrar before travel.', 'Request KHF tryout permission letter timeline before flights are booked.', 'Confirm whether IIHF transfer, tryout approval, or both are required.'],
      tags: ['Korea-to-Canada', 'Tryout', 'KHF', 'Hockey-Quebec', 'IIHF-Transfer', 'Insurance', '트라이아웃 허가', '대한아이스하키협회 허가서'],
      sources: ['Hockey Canada 2026-27 Articles, By-Laws and Regulations', 'IIHF International Transfer Regulations 2026'],
    },
    {
      title: 'Korea -> Canada Junior A full season',
      countries: ['Korea', 'Canada'],
      leagues: ['Junior A', 'LHJQ', 'LHJAAAQ'],
      agencies: ['Hockey Canada', 'Hockey Quebec', 'LHJQ/LHJAAAQ'],
      risk: 'Critical',
      confidence: 'Do not rely on this yet',
      answer: 'Potential conflict: Hockey Canada says teams below Major Junior generally cannot register Non-North American Imports. Korean Junior A participation must be clarified directly for Quebec leagues.',
      actions: ['Get written explanation from Hockey Canada/Hockey Quebec/LHJQ/LHJAAAQ.', 'Do not assume full-season registration is valid until the league confirms the exact pathway.'],
      tags: ['Korea-to-Canada', 'Junior-A', 'Import', 'Non-North-American-Import', 'HCR', '비북미 임포트 선수'],
      sources: ['Hockey Canada 2026-27 Articles, By-Laws and Regulations'],
    },
    {
      title: 'Korea -> QMJHL / CHL',
      countries: ['Korea', 'Canada'],
      leagues: ['CHL', 'QMJHL'],
      agencies: ['CHL', 'QMJHL', 'Hockey Canada'],
      risk: 'Critical',
      confidence: 'Needs written confirmation',
      answer: 'A Korean player likely needs CHL import rights and an open import slot unless the player has recognized Canada/U.S. residency status. Public CHL-team language does not define residency proof.',
      actions: ['Confirm with CHL/QMJHL central registry.', 'Ask whether mid-season roster addition is possible if the player was not selected in the CHL Import Draft.'],
      tags: ['CHL', 'QMJHL', 'Import-Draft', 'Residency-Status', 'CHL 임포트 드래프트', '거주 자격'],
      sources: ['Saint John Sea Dogs CHL Import Draft page', 'CHL 2026 Import Draft announcement'],
    },
    {
      title: 'Canada Junior A -> QMJHL affiliate / call-up',
      countries: ['Canada'],
      leagues: ['Junior A', 'CHL', 'QMJHL'],
      agencies: ['Hockey Canada', 'Hockey Quebec', 'QMJHL'],
      risk: 'Critical',
      confidence: 'Primary source confirmed',
      answer: 'Hockey Canada says Non-North American Imports are ineligible to advance to a higher division or category as affiliated players. Do not assume a Korean Junior A player can be called up by QMJHL as an AP.',
      actions: ['Ask QMJHL/Hockey Canada for a written ruling on the exact roster process.', 'Treat full roster/import-rights process as separate from AP call-up until confirmed.'],
      tags: ['Affiliated-Player', 'Call-Up', 'Junior-A', 'QMJHL', '제휴 선수', '콜업 선수'],
      sources: ['Hockey Canada 2026-27 Articles, By-Laws and Regulations'],
    },
    {
      title: 'Canada Junior A -> QMJHL full roster',
      countries: ['Canada'],
      leagues: ['Junior A', 'CHL', 'QMJHL'],
      agencies: ['CHL', 'QMJHL', 'Hockey Canada', 'Hockey Quebec', 'LHJQ/LHJAAAQ'],
      risk: 'High',
      confidence: 'Needs written confirmation',
      answer: 'Probably possible only through full release, registration, and CHL/QMJHL import-rights process, not a simple call-up.',
      actions: ['Confirm import draft rights, release, HCR/Hockey Quebec process, KHF/IIHF status.', 'Ask whether the current Junior A team must release the player before QMJHL registration.'],
      tags: ['Release', 'Import-Draft', 'HCR', 'IIHF-Transfer', '릴리즈', '이적'],
      sources: ['Hockey Canada 2026-27 Articles, By-Laws and Regulations', 'Saint John Sea Dogs CHL Import Draft page'],
    },
    {
      title: 'Canada -> U.S. junior',
      countries: ['Canada', 'United States', 'Korea'],
      leagues: ['USA Hockey', 'Junior A'],
      agencies: ['USA Hockey', 'Hockey Canada', 'IIHF', 'Korean Hockey Federation'],
      risk: 'High',
      confidence: 'Phone call required',
      answer: 'Governed by USA Hockey/Hockey Canada transfer processes and possibly IIHF if the Korean player is under limited transfer.',
      actions: ['Use USA Hockey transfer department and Hockey Canada agreement.', 'Confirm whether KHF must approve movement when the home federation is still Korea.'],
      tags: ['Canada-to-US', 'IIHF-Transfer', 'Transfer-Deadline', 'Release', '이적 마감일'],
      sources: ['USA Hockey Forms & Rulebook', 'IIHF International Transfer Regulations 2026'],
    },
    {
      title: 'U.S. -> Canada junior',
      countries: ['United States', 'Canada', 'Korea'],
      leagues: ['USA Hockey', 'Hockey Canada', 'Junior A'],
      agencies: ['USA Hockey', 'Hockey Canada', 'Hockey Quebec', 'IIHF'],
      risk: 'High',
      confidence: 'Phone call required',
      answer: 'Governed by USA Hockey/Hockey Canada movement rules plus Hockey Canada registration, release, transfer fee, roster, and import-status review.',
      actions: ['Confirm release, transfer, fees, roster status, import status, and any IIHF requirement before travel.'],
      tags: ['US-to-Canada', 'HCR', 'IIHF-Transfer', 'Import', 'Transfer-Deadline'],
      sources: ['USA Hockey Forms & Rulebook', 'Hockey Canada 2026-27 Articles, By-Laws and Regulations'],
    },
    {
      title: 'Korean player seeking USA Hockey non-import waiver',
      countries: ['Korea', 'United States'],
      leagues: ['USA Hockey'],
      agencies: ['USA Hockey'],
      risk: 'High',
      confidence: 'Primary source confirmed',
      answer: 'USA Hockey non-import waiver depends on at least three consecutive USA Hockey youth seasons while residing in the U.S. before juniors. Junior hockey outside USA Hockey likely blocks the waiver.',
      actions: ['Confirm each player with transfers@usahockey.org.', 'Collect proof of USA Hockey membership, youth participation, and U.S. residence.'],
      tags: ['USA-Hockey', 'Non-Import-Waiver', 'Residency-Status', '거주 자격'],
      sources: ['USA Hockey 2026-27 Request for Non-Import Classification Waiver'],
    },
    {
      title: 'CHL non-import theory: Canadian apartment lease',
      countries: ['Korea', 'Canada'],
      leagues: ['CHL', 'QMJHL'],
      agencies: ['CHL', 'QMJHL'],
      risk: 'Critical',
      confidence: 'Do not rely on this yet',
      answer: 'Probably not enough. A lease is not the same as legal residency status, but CHL/QMJHL must define what documents count.',
      actions: ['Ask CHL/QMJHL what residency status means.', 'Do not advise families that housing changes import classification.'],
      tags: ['Housing', 'Residency-Status', 'Import-Draft', 'Apartment-Lease', '아파트 임대', '렌트 계약'],
      sources: ['Saint John Sea Dogs CHL Import Draft page'],
    },
    {
      title: 'CHL non-import theory: one year playing in Canada',
      countries: ['Korea', 'Canada'],
      leagues: ['CHL', 'QMJHL', 'Junior A'],
      agencies: ['CHL', 'QMJHL', 'Hockey Canada'],
      risk: 'Critical',
      confidence: 'Do not rely on this yet',
      answer: 'Probably not enough by itself. Hockey Canada says import status can carry into later Hockey Canada registrations, and CHL-specific import treatment needs direct confirmation.',
      actions: ['Ask CHL/QMJHL and Hockey Canada for written confirmation.', 'Keep families from treating one Canadian season as an automatic reset.'],
      tags: ['Import', 'Residency-Status', 'Junior-A', 'CHL', '비북미 임포트 선수'],
      sources: ['Hockey Canada 2026-27 Articles, By-Laws and Regulations', 'Saint John Sea Dogs CHL Import Draft page'],
    },
    {
      title: 'Club / prep movement before junior',
      countries: ['Korea', 'Canada', 'United States'],
      leagues: ['Club', 'Prep', 'USA Hockey', 'Hockey Canada'],
      agencies: ['USA Hockey', 'Hockey Canada', 'IIHF', 'Korean Hockey Federation'],
      risk: 'High',
      confidence: 'Phone call required',
      answer: 'School, club, prep, camp, and sanctioned team activity can trigger different permission, insurance, and transfer questions. Treat activity type as a rules variable.',
      actions: ['Confirm whether the activity is private skate, team practice, exhibition, rookie camp, school game, or sanctioned league game.', 'Confirm insurance and transfer status before the player skates.'],
      tags: ['Club', 'Prep', 'Tryout', 'Insurance', 'IIHF-Transfer', '보험 적용'],
      sources: ['IIHF International Transfer Regulations 2026', 'USA Hockey Forms & Rulebook', 'Hockey Canada 2026-27 Articles, By-Laws and Regulations'],
    },
  ],
  checklist: [
    ['KHF tryout permission letter or written confirmation that it is not required', 'KHF / player family / Northstar', 'Korea -> Canada tryout, camp, practice', 'Open'],
    ['League registrar confirms player may step on ice for the exact activity', 'Target league office', 'Tryout, camp, practice, exhibition, games', 'Required before travel'],
    ['Hockey Canada / Hockey Quebec registration or tryout pathway identified in writing', 'Hockey Canada / Hockey Quebec', 'Quebec Junior A, QMJHL, sanctioned activity', 'Open'],
    ['IIHF transfer, limited transfer, or written no-transfer-needed answer', 'IIHF / federations', 'International movement', 'Open'],
    ['Insurance coverage confirmed for activity type', 'League / team / insurer', 'Private skate, tryout, camp, exhibition', 'Open'],
    ['Import status classified and recorded', 'League / governing body', 'Junior A, CHL/QMJHL, USA Hockey junior', 'Open'],
    ['Release and transfer deadlines checked', 'Current team / target league', 'Canada-U.S., Junior A -> CHL/QMJHL', 'Open'],
  ],
  questions: [
    ['CHL-001', 'What exact documents prove residency status in Canada or the U.S. for CHL import classification?', 'CHL / QMJHL', 'Critical', 'Open'],
    ['CHL-004', 'Can a Korean player who was not selected in the CHL Import Draft be rostered by a QMJHL team mid-season?', 'CHL / QMJHL', 'Critical', 'Open'],
    ['HC-001', 'How does Hockey Canada Non-North American Import language apply to Quebec Junior A / LHJQ / LHJAAAQ?', 'Hockey Canada / Hockey Quebec', 'Critical', 'Open'],
    ['HC-002', 'What exact approval is required before a Korean player can participate in a 15-day tryout in Quebec Junior A?', 'Hockey Canada / Hockey Quebec', 'Critical', 'Open'],
    ['HC-003', 'Can a Korean Non-North American Import advance from Junior A to Major Junior as an affiliated player?', 'Hockey Canada / Hockey Quebec', 'Critical', 'Open'],
    ['KHF-001', 'What exact letter does KHF issue for a Korean player to attend a Canada tryout?', 'Korean Hockey Federation', 'Critical', 'Open'],
    ['USAH-001', 'Can a Korean player who played Junior A in Canada apply for USA Hockey non-import classification?', 'USA Hockey', 'High', 'Open'],
    ['ACT-004', 'Can a Korean player attend rookie camp before full registration?', 'Hockey Canada / Hockey Quebec / League', 'High', 'Open'],
    ['CASE-006', 'If a Korean Junior A player is not eligible as an affiliated player, what exact roster process must a QMJHL team use?', 'QMJHL / Hockey Canada', 'Critical', 'Open'],
  ],
  callNotes: [
    {
      date: 'Not started',
      agency: 'Hockey Canada / Hockey Quebec',
      contact: 'Registrar or transfer desk',
      topic: 'Korea -> Quebec Junior A tryout and registration pathway',
      answer: 'Need phone call and written follow-up before relying on any operational conclusion.',
      confidence: 'Phone call required',
      followUp: 'Ask for exact KHF letter, HCR step, IIHF transfer requirement, and insurance status before the player skates.',
    },
    {
      date: 'Not started',
      agency: 'CHL / QMJHL',
      contact: 'Central registry or player eligibility contact',
      topic: 'CHL import status, residency proof, and Junior A -> QMJHL pathway',
      answer: 'Need written confirmation on import rights, residency status, mid-season roster process, and AP ineligibility impact.',
      confidence: 'Needs written confirmation',
      followUp: 'Ask whether a lease or one Canadian season changes import classification, and what process applies if no CHL import rights are held.',
    },
    {
      date: 'Not started',
      agency: 'Korean Hockey Federation',
      contact: 'International transfer or player clearance contact',
      topic: 'Tryout permission letter and transfer approval timeline',
      answer: 'Need process owner, required documents, and expected issuance timing.',
      confidence: 'Phone call required',
      followUp: 'Create a reusable pre-travel checklist once KHF confirms the document name and request process.',
    },
  ],
  sources: [
    ['IIHF International Transfer Regulations 2026', 'International transfers, deadlines, under-18 transfers, limited/unlimited transfers', 'https://blob.iihf.com/iihf-media/iihfmvc/media/downloads/regulations/2026/2026_iihf_international_transfer_regulations.pdf'],
    ['Hockey Canada 2026-27 Articles, By-Laws and Regulations', 'Import definitions, Non-North American Import rules, junior quotas, affiliation restrictions', 'https://cdn.hockeycanada.ca/hockey-canada/Corporate/About/Downloads/2026-27-bylaws-e.pdf'],
    ['USA Hockey Forms & Rulebook', 'Official USA Hockey junior rulebook and forms page', 'https://www.usahockey.com/page/show/887403-forms%20%26%20rulebook'],
    ['Saint John Sea Dogs CHL Import Draft page', 'CHL-team statement about import players and Canada/U.S. residency status', 'https://chl.ca/lhjmq-seadogs/chl-import-draft/'],
    ['CHL 2026 Import Draft announcement', 'Import draft results and roster slot context', 'https://chl.ca/article/114-players-selected-during-the-2026-chl-import-draft/'],
    ['CHL 2025 Import Draft announcement', 'Import draft expansion context', 'https://chl.ca/article/2025-chl-import-draft-set-to-take-place-july-2-at-1100-a-m-et/'],
  ],
  koreanLabels: ['임포트 선수 분류', '비북미 임포트 선수', 'CHL 임포트 드래프트', '거주 자격', '아파트 임대', '주니어 A에서 QMJHL 이동', '제휴 선수', '콜업 선수', '트라이아웃 허가', 'IIHF 국제 이적', '대한아이스하키협회 허가서', 'HCR', '릴리즈', '이적 마감일', '보험 적용'],
};
